debug: true

security:
  user:
    password: none
cors:
  allowed:
      origins: "*"
  
          
spring:
  data:
    rest:
      base-uri: /
#  http:
#   multipart:
#      enabled: true
#      max-file-size: -1
#      max-request-size: 1024Mb
      
---

spring:
  profiles: default, local

  datasource:
    url: jdbc:mysql://localhost:3306/priyanka
    username: bahubali
    password: bahubali
    max-active: 10
    max-age: 10000
    connection-timeout: 10000
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
   port: 8086



